"""Fase 3: maestros, inventario e importador de Excel.

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-22

Crea los maestros operativos (categorias de producto y de punto de venta,
unidades, productos y terceros), el inventario con su trazabilidad y las
tablas de staging del importador.

Las tres unidades canonicas se siembran aqui porque son catalogo tecnico, no
datos de negocio: sin ellas ningun producto puede referenciar su unidad. No se
siembra ningun producto, tercero ni existencia: esos datos solo entran por el
importador confirmado por el usuario.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Mismo blindaje que las fases anteriores: Supabase publica "public" por
#: PostREST con la publishable key, de modo que una tabla sin RLS quedaria
#: legible por cualquiera que tenga esa clave. Con RLS activo y sin policies,
#: anon y authenticated no pueden leer ni escribir nada. El backend entra con
#: la credencial de servicio y no se ve afectado.
NEW_TABLES = (
    "product_categories",
    "pos_categories",
    "units_of_measure",
    "products",
    "partners",
    "stock_locations",
    "stock_balances",
    "stock_movements",
    "import_batches",
    "import_rows",
)

_REVOKE_SQL = """
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{role}') THEN
        REVOKE ALL ON TABLE public.{table} FROM {role};
    END IF;
END
$$
"""

#: Unidades canonicas. El maestro escribe "gr" y la hoja de stock "g": el
#: importador traduce ambas a "g" y la tabla solo guarda codigos canonicos.
UNITS = [
    {
        "code": "g",
        "name": "Gramo",
        "symbol": "g",
        "dimension": "MASS",
        "factor_to_base": "1",
        "is_base": True,
    },
    {
        "code": "kg",
        "name": "Kilogramo",
        "symbol": "kg",
        "dimension": "MASS",
        "factor_to_base": "1000",
        "is_base": False,
    },
    {
        "code": "unit",
        "name": "Unidad",
        "symbol": "u",
        "dimension": "COUNT",
        "factor_to_base": "1",
        "is_base": True,
    },
]


def _lock_down(table: str) -> None:
    op.execute(f"ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY")
    for role in ("anon", "authenticated"):
        op.execute(_REVOKE_SQL.format(role=role, table=table))


def _seed_units() -> None:
    table = sa.table(
        "units_of_measure",
        sa.column("code", sa.String),
        sa.column("name", sa.String),
        sa.column("symbol", sa.String),
        sa.column("dimension", sa.String),
        sa.column("factor_to_base", sa.Numeric),
        sa.column("is_base", sa.Boolean),
    )
    op.bulk_insert(table, UNITS)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_batches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_by_name", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "file_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_import_batches_file_hash_sha256")
        ),
        sa.CheckConstraint(
            "status IN ('UPLOADED', 'ANALYZED', 'READY', 'COMMITTED', 'FAILED', 'CANCELLED')",
            name=op.f("ck_import_batches_status_allowed"),
        ),
        sa.CheckConstraint("file_size > 0", name=op.f("ck_import_batches_file_size_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
    )
    op.create_index("ix_import_batches_created", "import_batches", ["created_at"], unique=False)
    op.create_index("ix_import_batches_hash", "import_batches", ["file_hash"], unique=False)
    op.create_table(
        "pos_categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(btrim(name)) > 0", name=op.f("ck_pos_categories_name_not_blank")
        ),
        sa.CheckConstraint(
            "parent_id IS NULL OR parent_id <> id", name=op.f("ck_pos_categories_parent_not_self")
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["pos_categories.id"],
            name=op.f("fk_pos_categories_parent_id_pos_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pos_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_pos_categories_name")),
    )
    op.create_table(
        "product_categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("display_path", sa.String(length=400), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(btrim(display_path)) > 0",
            name=op.f("ck_product_categories_display_path_not_blank"),
        ),
        sa.CheckConstraint(
            "length(btrim(name)) > 0", name=op.f("ck_product_categories_name_not_blank")
        ),
        sa.CheckConstraint(
            "parent_id IS NULL OR parent_id <> id",
            name=op.f("ck_product_categories_parent_not_self"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["product_categories.id"],
            name=op.f("fk_product_categories_parent_id_product_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_categories")),
        sa.UniqueConstraint("display_path", name=op.f("uq_product_categories_display_path")),
        sa.UniqueConstraint("parent_id", "name", name="uq_product_categories_parent_name"),
    )
    op.create_table(
        "stock_locations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(btrim(name)) > 0", name=op.f("ck_stock_locations_name_not_blank")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_locations")),
        sa.UniqueConstraint("name", name=op.f("uq_stock_locations_name")),
    )
    op.create_table(
        "units_of_measure",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("dimension", sa.String(length=16), nullable=False),
        sa.Column("factor_to_base", sa.Numeric(precision=24, scale=12), nullable=False),
        sa.Column("is_base", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "dimension IN ('MASS', 'COUNT')", name=op.f("ck_units_of_measure_dimension_allowed")
        ),
        sa.CheckConstraint(
            "NOT is_base OR factor_to_base = 1", name=op.f("ck_units_of_measure_base_factor_is_one")
        ),
        sa.CheckConstraint("factor_to_base > 0", name=op.f("ck_units_of_measure_factor_positive")),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_units_of_measure")),
    )
    op.create_index(
        "ix_units_of_measure_dimension", "units_of_measure", ["dimension"], unique=False
    )
    op.create_table(
        "import_rows",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("entity", sa.String(length=24), nullable=False),
        sa.Column("sheet_name", sa.String(length=120), nullable=False),
        sa.Column("source_row", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("normalized", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("candidates", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resolution", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("target_table", sa.String(length=64), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "action IN ('CREATE', 'UPDATE', 'SKIP', 'ERROR')",
            name=op.f("ck_import_rows_action_allowed"),
        ),
        sa.CheckConstraint(
            "entity IN ('PRODUCT_CATEGORY', 'POS_CATEGORY', 'UNIT', 'PRODUCT', "
            "'PARTNER', 'LOCATION', 'STOCK', 'RECIPE')",
            name=op.f("ck_import_rows_entity_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('READY', 'REVIEW_REQUIRED', 'RESOLVED', 'BLOCKED', 'COMMITTED')",
            name=op.f("ck_import_rows_status_allowed"),
        ),
        sa.CheckConstraint("source_row > 0", name=op.f("ck_import_rows_source_row_positive")),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["import_batches.id"],
            name=op.f("fk_import_rows_batch_id_import_batches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_rows")),
        sa.UniqueConstraint("batch_id", "entity", "source_row", name="uq_import_rows_batch_id"),
    )
    op.create_index(
        "ix_import_rows_batch_entity",
        "import_rows",
        ["batch_id", "entity", "sort_order"],
        unique=False,
    )
    op.create_index("ix_import_rows_status", "import_rows", ["batch_id", "status"], unique=False)
    op.create_table(
        "partners",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("document_type", sa.String(length=16), nullable=True),
        sa.Column("document_number", sa.String(length=20), nullable=True),
        sa.Column("address", sa.String(length=240), nullable=True),
        sa.Column("reference", sa.String(length=240), nullable=True),
        sa.Column("ubigeo_code", sa.String(length=6), nullable=True),
        sa.Column("district", sa.String(length=120), nullable=True),
        sa.Column("province", sa.String(length=100), nullable=True),
        sa.Column("department", sa.String(length=80), nullable=True),
        sa.Column("country", sa.String(length=80), nullable=True),
        sa.Column("email", sa.String(length=160), nullable=True),
        sa.Column("mobile", sa.String(length=32), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "document_type IS NULL OR document_type IN ('RUC', 'DNI', 'CE', 'PASSPORT', 'OTHER')",
            name=op.f("ck_partners_document_type_allowed"),
        ),
        sa.CheckConstraint(
            "role IN ('CLIENT', 'SUPPLIER', 'BOTH')", name=op.f("ck_partners_role_allowed")
        ),
        sa.CheckConstraint(
            "(document_type IS NULL) = (document_number IS NULL)",
            name=op.f("ck_partners_document_pair_complete"),
        ),
        sa.CheckConstraint("length(btrim(name)) > 0", name=op.f("ck_partners_name_not_blank")),
        sa.ForeignKeyConstraint(
            ["ubigeo_code"],
            ["ubigeo_districts.code"],
            name=op.f("fk_partners_ubigeo_code_ubigeo_districts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_partners")),
    )
    op.create_index("ix_partners_name", "partners", ["name"], unique=False)
    op.create_index("ix_partners_role_active", "partners", ["role", "active"], unique=False)
    op.create_index(
        "uq_partners_document",
        "partners",
        ["document_type", "document_number"],
        unique=True,
        postgresql_where=sa.text("document_number IS NOT NULL"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("internal_reference", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("product_type", sa.String(length=24), nullable=False),
        sa.Column("product_category_id", sa.Integer(), nullable=False),
        sa.Column("pos_category_id", sa.Integer(), nullable=True),
        sa.Column("base_uom_code", sa.String(length=16), nullable=True),
        sa.Column("purchase_uom_code", sa.String(length=16), nullable=True),
        sa.Column("cost", sa.Numeric(precision=24, scale=12), nullable=True),
        sa.Column("sale_price", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("sale_tax_rate", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("purchase_tax_rate", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("sellable", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("purchasable", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "available_in_pos", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "product_type IN ('RAW_MATERIAL', 'PREPARED_MATERIAL', 'FINISHED_PRODUCT', 'SERVICE')",
            name=op.f("ck_products_product_type_allowed"),
        ),
        sa.CheckConstraint("cost IS NULL OR cost >= 0", name=op.f("ck_products_cost_not_negative")),
        sa.CheckConstraint(
            "length(btrim(internal_reference)) > 0", name=op.f("ck_products_reference_not_blank")
        ),
        sa.CheckConstraint("length(btrim(name)) > 0", name=op.f("ck_products_name_not_blank")),
        sa.CheckConstraint(
            "sale_price IS NULL OR sale_price >= 0",
            name=op.f("ck_products_sale_price_not_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["base_uom_code"],
            ["units_of_measure.code"],
            name=op.f("fk_products_base_uom_code_units_of_measure"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pos_category_id"],
            ["pos_categories.id"],
            name=op.f("fk_products_pos_category_id_pos_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_category_id"],
            ["product_categories.id"],
            name=op.f("fk_products_product_category_id_product_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_uom_code"],
            ["units_of_measure.code"],
            name=op.f("fk_products_purchase_uom_code_units_of_measure"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("internal_reference", name=op.f("uq_products_internal_reference")),
    )
    op.create_index("ix_products_category", "products", ["product_category_id"], unique=False)
    op.create_index("ix_products_name", "products", ["name"], unique=False)
    op.create_index("ix_products_type_active", "products", ["product_type", "active"], unique=False)
    op.create_table(
        "stock_balances",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column(
            "quantity",
            sa.Numeric(precision=24, scale=12),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity >= 0", name=op.f("ck_stock_balances_quantity_not_negative")),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["stock_locations.id"],
            name=op.f("fk_stock_balances_location_id_stock_locations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_stock_balances_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_balances")),
        sa.UniqueConstraint("product_id", "location_id", name="uq_stock_balances_product_id"),
    )
    op.create_index("ix_stock_balances_location", "stock_balances", ["location_id"], unique=False)
    op.create_table(
        "stock_movements",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("movement_type", sa.String(length=24), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=12), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=24, scale=12), nullable=False),
        sa.Column("uom_code", sa.String(length=16), nullable=False),
        sa.Column("import_batch_id", sa.Integer(), nullable=True),
        sa.Column("reason", sa.String(length=240), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_by_name", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "movement_type IN ('INITIAL_IMPORT', 'ADJUSTMENT', 'IN', 'OUT')",
            name=op.f("ck_stock_movements_movement_type_allowed"),
        ),
        sa.CheckConstraint(
            "balance_after >= 0", name=op.f("ck_stock_movements_balance_after_not_negative")
        ),
        sa.CheckConstraint("quantity <> 0", name=op.f("ck_stock_movements_quantity_not_zero")),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_stock_movements_import_batch_id_import_batches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["stock_locations.id"],
            name=op.f("fk_stock_movements_location_id_stock_locations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_stock_movements_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["uom_code"],
            ["units_of_measure.code"],
            name=op.f("fk_stock_movements_uom_code_units_of_measure"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_movements")),
    )
    op.create_index(
        "ix_stock_movements_batch", "stock_movements", ["import_batch_id"], unique=False
    )
    op.create_index(
        "ix_stock_movements_product_created",
        "stock_movements",
        ["product_id", "created_at"],
        unique=False,
    )

    for table in NEW_TABLES:
        _lock_down(table)
    _seed_units()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_stock_movements_product_created", table_name="stock_movements")
    op.drop_index("ix_stock_movements_batch", table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_index("ix_stock_balances_location", table_name="stock_balances")
    op.drop_table("stock_balances")
    op.drop_index("ix_products_type_active", table_name="products")
    op.drop_index("ix_products_name", table_name="products")
    op.drop_index("ix_products_category", table_name="products")
    op.drop_table("products")
    op.drop_index(
        "uq_partners_document",
        table_name="partners",
        postgresql_where=sa.text("document_number IS NOT NULL"),
    )
    op.drop_index("ix_partners_role_active", table_name="partners")
    op.drop_index("ix_partners_name", table_name="partners")
    op.drop_table("partners")
    op.drop_index("ix_import_rows_status", table_name="import_rows")
    op.drop_index("ix_import_rows_batch_entity", table_name="import_rows")
    op.drop_table("import_rows")
    op.drop_index("ix_units_of_measure_dimension", table_name="units_of_measure")
    op.drop_table("units_of_measure")
    op.drop_table("stock_locations")
    op.drop_table("product_categories")
    op.drop_table("pos_categories")
    op.drop_index("ix_import_batches_hash", table_name="import_batches")
    op.drop_index("ix_import_batches_created", table_name="import_batches")
    op.drop_table("import_batches")
    # ### end Alembic commands ###
