"""Punto de entrada de la aplicacion FastAPI."""

from __future__ import annotations

import logging
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.api.health import router as health_router
from app.api.v1.router import api_v1_router
from app.auth.csrf import CSRF_HEADER_NAME
from app.auth.middleware import CsrfMiddleware
from app.core.config import Settings, get_settings
from app.core.errors import ServiceUnavailableError
from app.core.handlers import register_exception_handlers
from app.core.logging import configure_logging
from app.db.session import dispose_engine
from app.services.supabase_auth import HttpSupabaseAuthClient

logger = logging.getLogger(__name__)


def _log_startup_summary(settings: Settings) -> None:
    """Registra la configuracion efectiva sin revelar ningun secreto."""
    logger.info(
        "Iniciando %s v%s (env=%s) | cors=%s | cookies: secure=%s samesite=%s domain=%s | "
        "supabase=%s | database=%s",
        settings.APP_NAME,
        settings.APP_VERSION,
        settings.APP_ENV.value,
        settings.frontend_origins,
        settings.COOKIE_SECURE,
        settings.COOKIE_SAMESITE,
        settings.COOKIE_DOMAIN or "(host actual)",
        "configurado" if settings.supabase_configured else "NO CONFIGURADO",
        "configurada" if settings.database_configured else "NO CONFIGURADA",
    )
    if settings.csrf_secret_autogenerated:
        logger.warning(
            "CSRF_SECRET no fue provisto: se genero uno efimero para este proceso. "
            "Defina CSRF_SECRET fuera de desarrollo local."
        )


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    settings = get_settings()
    configure_logging(settings)
    _log_startup_summary(settings)

    # El cliente de Supabase se crea una sola vez y reutiliza el pool de
    # conexiones HTTP. Si falta configuracion la aplicacion sigue viva (para
    # que /live y /ready puedan diagnosticar), pero /auth responde 503.
    app.state.supabase_auth = None
    if settings.supabase_configured:
        try:
            app.state.supabase_auth = HttpSupabaseAuthClient(settings)
        except ServiceUnavailableError:
            logger.error("No se pudo inicializar el cliente de Supabase Auth")

    try:
        yield
    finally:
        client = getattr(app.state, "supabase_auth", None)
        if isinstance(client, HttpSupabaseAuthClient):
            await client.aclose()
        await dispose_engine()


def create_app(settings: Settings | None = None) -> FastAPI:
    """Construye la aplicacion. Parametrizable para facilitar las pruebas."""
    settings = settings or get_settings()
    is_production = settings.is_production

    app = FastAPI(
        title=settings.APP_NAME,
        version=settings.APP_VERSION,
        lifespan=lifespan,
        # La documentacion interactiva queda fuera de produccion.
        docs_url=None if is_production else "/docs",
        redoc_url=None,
        openapi_url=None if is_production else "/openapi.json",
    )

    # El middleware anadido en ultimo lugar es el mas externo: CORS debe
    # envolver a CSRF para que incluso las respuestas 403 lleven cabeceras CORS
    # y el navegador pueda leerlas.
    app.add_middleware(CsrfMiddleware, settings=settings)
    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.frontend_origins,
        allow_credentials=True,
        allow_methods=["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
        allow_headers=["Content-Type", "Accept", CSRF_HEADER_NAME],
        max_age=600,
    )

    register_exception_handlers(app)

    app.include_router(health_router)
    app.include_router(api_v1_router)
    return app


app = create_app()
