"""Modelos ORM de la aplicacion."""

from app.db.base import Base
from app.models.audit import AuditAction, AuditEvent
from app.models.catalog import CurrencyCatalog, SequencePatternPreset, UbigeoDistrict
from app.models.firings import (
    Firing,
    FiringKilnSession,
    FiringLine,
    FiringStatus,
    FiringType,
    Kiln,
    KilnOccupancyFactor,
    KilnRate,
)
from app.models.identity import (
    IdentityDocumentType,
    IdentityLookupAuditEvent,
    IdentityLookupCache,
    IdentityLookupDailyStat,
    IdentityLookupProviderMetric,
    ProviderName,
)
from app.models.importing import (
    ImportAction,
    ImportBatch,
    ImportEntity,
    ImportRow,
    ImportRowStatus,
    ImportStatus,
)
from app.models.inventory import MovementType, StockBalance, StockLocation, StockMovement
from app.models.masters import (
    DocumentType,
    Partner,
    PartnerRole,
    PosCategory,
    Product,
    ProductCategory,
    ProductType,
    UnitOfMeasure,
    UomDimension,
)
from app.models.production import (
    ProductionOrder,
    ProductionOrderLine,
    ProductionOrderStatus,
)
from app.models.profile import Profile, UserRole
from app.models.prototype_quotations import (
    PrototypeQuotation,
    PrototypeQuotationMaterial,
    PrototypeQuotationPaymentStatus,
    PrototypeQuotationStatus,
)
from app.models.prototypes import (
    Prototype,
    PrototypeApproval,
    PrototypeMaterialLine,
    PrototypeMaterialRole,
    PrototypeStatus,
)
from app.models.quotations import (
    Additional,
    AdditionalFormulaType,
    CommercialLineKind,
    OtherCost,
    OtherCostCalculationType,
    Quotation,
    QuotationAdditional,
    QuotationCommercialLine,
    QuotationItem,
    QuotationOtherCost,
    QuotationProductPriceUpdate,
    QuotationStatus,
    QuotationTechnique,
    QuotationWorkflow,
    Technique,
    TechniqueFormulaType,
)
from app.models.recipes import (
    Recipe,
    RecipeComponentType,
    RecipeLine,
    RecipeStatus,
    RecipeVersion,
)
from app.models.sequence import (
    DocumentSequence,
    DocumentSequenceIssue,
    ResetPolicy,
    SequenceType,
)
from app.models.settings import BankAccount, CommercialSettings, CompanySettings

__all__ = [
    "Additional",
    "AdditionalFormulaType",
    "AuditAction",
    "AuditEvent",
    "BankAccount",
    "Base",
    "CommercialLineKind",
    "CommercialSettings",
    "CompanySettings",
    "CurrencyCatalog",
    "DocumentSequence",
    "DocumentSequenceIssue",
    "DocumentType",
    "Firing",
    "FiringKilnSession",
    "FiringLine",
    "FiringStatus",
    "FiringType",
    "IdentityDocumentType",
    "IdentityLookupAuditEvent",
    "IdentityLookupCache",
    "IdentityLookupDailyStat",
    "IdentityLookupProviderMetric",
    "ImportAction",
    "ImportBatch",
    "ImportEntity",
    "ImportRow",
    "ImportRowStatus",
    "ImportStatus",
    "Kiln",
    "KilnOccupancyFactor",
    "KilnRate",
    "MovementType",
    "OtherCost",
    "OtherCostCalculationType",
    "Partner",
    "PartnerRole",
    "PosCategory",
    "Product",
    "ProductCategory",
    "ProductType",
    "ProductionOrder",
    "ProductionOrderLine",
    "ProductionOrderStatus",
    "Profile",
    "Prototype",
    "PrototypeApproval",
    "PrototypeMaterialLine",
    "PrototypeMaterialRole",
    "PrototypeQuotation",
    "PrototypeQuotationMaterial",
    "PrototypeQuotationPaymentStatus",
    "PrototypeQuotationStatus",
    "PrototypeStatus",
    "ProviderName",
    "Quotation",
    "QuotationAdditional",
    "QuotationCommercialLine",
    "QuotationItem",
    "QuotationOtherCost",
    "QuotationProductPriceUpdate",
    "QuotationStatus",
    "QuotationTechnique",
    "QuotationWorkflow",
    "Recipe",
    "RecipeComponentType",
    "RecipeLine",
    "RecipeStatus",
    "RecipeVersion",
    "ResetPolicy",
    "SequencePatternPreset",
    "SequenceType",
    "StockBalance",
    "StockLocation",
    "StockMovement",
    "Technique",
    "TechniqueFormulaType",
    "UbigeoDistrict",
    "UnitOfMeasure",
    "UomDimension",
    "UserRole",
]
