"""Reglas de configuracion y endurecimiento por entorno."""

from __future__ import annotations

import pytest
from pydantic import ValidationError

from app.core.config import ConfigurationError, Settings

SECRETO_VALIDO = "un-secreto-suficientemente-largo-para-produccion"


def test_samesite_none_exige_secure() -> None:
    with pytest.raises(ValidationError, match="COOKIE_SECURE"):
        Settings(COOKIE_SAMESITE="none", COOKIE_SECURE=False)


def test_samesite_none_con_secure_es_valido() -> None:
    settings = Settings(COOKIE_SAMESITE="none", COOKIE_SECURE=True)

    assert settings.COOKIE_SAMESITE == "none"


def test_samesite_se_normaliza_a_minusculas() -> None:
    assert Settings(COOKIE_SAMESITE="LAX").COOKIE_SAMESITE == "lax"


def test_produccion_rechaza_cookies_inseguras() -> None:
    with pytest.raises(ValidationError, match="COOKIE_SECURE"):
        Settings(APP_ENV="production", COOKIE_SECURE=False, CSRF_SECRET=SECRETO_VALIDO)


def test_produccion_exige_un_csrf_secret_largo() -> None:
    with pytest.raises(ValidationError, match="CSRF_SECRET"):
        Settings(APP_ENV="production", COOKIE_SECURE=True, CSRF_SECRET="corto")


def test_produccion_exige_configuracion_de_supabase() -> None:
    with pytest.raises(ValidationError, match="SUPABASE_URL"):
        Settings(
            APP_ENV="production",
            COOKIE_SECURE=True,
            CSRF_SECRET=SECRETO_VALIDO,
            SUPABASE_URL="",
        )


def test_produccion_exige_un_identity_hash_secret_largo() -> None:
    with pytest.raises(ValidationError, match="IDENTITY_HASH_SECRET"):
        Settings(
            APP_ENV="production",
            COOKIE_SECURE=True,
            CSRF_SECRET=SECRETO_VALIDO,
            IDENTITY_HASH_SECRET="corto",
        )


def test_produccion_valida_es_aceptada() -> None:
    settings = Settings(
        APP_ENV="production",
        COOKIE_SECURE=True,
        COOKIE_SAMESITE="none",
        CSRF_SECRET=SECRETO_VALIDO,
        IDENTITY_HASH_SECRET=SECRETO_VALIDO,
        SUPABASE_URL="https://proyecto.supabase.co",
        SUPABASE_PUBLISHABLE_KEY="clave",
        FRONTEND_ORIGINS="https://app.example.com",
    )

    assert settings.is_production
    assert settings.frontend_origins == ["https://app.example.com"]


def test_cors_rechaza_el_comodin() -> None:
    settings = Settings(FRONTEND_ORIGINS="*")

    with pytest.raises(ConfigurationError):
        _ = settings.frontend_origins


def test_cors_admite_varios_origenes_con_espacios() -> None:
    settings = Settings(FRONTEND_ORIGINS=" http://a.test , https://b.test ")

    assert settings.frontend_origins == ["http://a.test", "https://b.test"]


def test_url_de_supabase_pierde_la_barra_final() -> None:
    assert Settings(SUPABASE_URL="https://x.supabase.co/").SUPABASE_URL == "https://x.supabase.co"


def test_dominio_de_cookie_vacio_equivale_a_no_definido() -> None:
    assert Settings(COOKIE_DOMAIN="   ").COOKIE_DOMAIN is None


def test_csrf_secret_se_genera_fuera_de_produccion() -> None:
    settings = Settings(APP_ENV="local", CSRF_SECRET="")

    assert settings.csrf_configured
    assert settings.csrf_secret_autogenerated


def test_identity_hash_secret_se_genera_fuera_de_produccion() -> None:
    settings = Settings(APP_ENV="local", IDENTITY_HASH_SECRET="")

    assert settings.IDENTITY_HASH_SECRET.get_secret_value()
    assert settings.identity_hash_secret_autogenerated


def test_los_secretos_no_aparecen_en_la_representacion() -> None:
    settings = Settings(
        CSRF_SECRET=SECRETO_VALIDO,
        IDENTITY_HASH_SECRET=SECRETO_VALIDO,
        SUPABASE_PUBLISHABLE_KEY="clave-publicable",
        DATABASE_URL="postgresql://usuario:password@host/db",
    )

    texto = repr(settings)

    assert SECRETO_VALIDO not in texto
    assert "clave-publicable" not in texto
    assert "password" not in texto
