"""Configuracion centralizada de la aplicacion.

Todos los valores se leen del entorno. Ningun secreto se escribe en el codigo
fuente ni se serializa en respuestas o logs: los campos sensibles usan
``SecretStr``, cuyo ``repr`` siempre aparece enmascarado.
"""

from __future__ import annotations

import secrets
from enum import StrEnum
from functools import lru_cache
from typing import Literal

from pydantic import PrivateAttr, SecretStr, field_validator, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

CookieSameSite = Literal["lax", "strict", "none"]

#: Longitud minima exigida a ``CSRF_SECRET`` en produccion.
MIN_CSRF_SECRET_LENGTH = 32


class AppEnv(StrEnum):
    """Entornos de ejecucion soportados."""

    LOCAL = "local"
    DEVELOPMENT = "development"
    STAGING = "staging"
    PRODUCTION = "production"


class ConfigurationError(RuntimeError):
    """La configuracion provista es invalida o insegura para el entorno."""


class Settings(BaseSettings):
    """Configuracion de BGreda resuelta desde variables de entorno."""

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    # ---- Aplicacion -----------------------------------------------------
    APP_ENV: AppEnv = AppEnv.LOCAL
    APP_NAME: str = "Cotizador Greda API"
    APP_VERSION: str = "0.1.0"
    LOG_LEVEL: str = "INFO"

    # ---- Supabase -------------------------------------------------------
    SUPABASE_URL: str = ""
    SUPABASE_PUBLISHABLE_KEY: SecretStr = SecretStr("")
    SUPABASE_TIMEOUT_SECONDS: float = 10.0

    # ---- Supabase Storage -----------------------------------------------
    # Clave con permiso de escritura en Storage (service_role / secret key).
    # Ignora RLS por completo: solo backend, jamas en una variable VITE_*.
    SUPABASE_SECRET_KEY: SecretStr = SecretStr("")
    SUPABASE_STORAGE_BUCKET: str = "greda-assets"
    #: Tamano maximo del logo. 2 MiB cubre cualquier logo razonable.
    LOGO_MAX_BYTES: int = 2 * 1024 * 1024

    # ---- Base de datos --------------------------------------------------
    # Credencial PostgreSQL usada por SQLAlchemy/Alembic. NO se deduce de
    # SUPABASE_URL ni de la publishable key: es una credencial distinta.
    DATABASE_URL: SecretStr = SecretStr("")

    # ---- CORS -----------------------------------------------------------
    # Lista separada por comas. Nunca "*": la API responde con cookies.
    FRONTEND_ORIGINS: str = "http://localhost:5173"

    # ---- Cookies --------------------------------------------------------
    COOKIE_SECURE: bool = True
    COOKIE_SAMESITE: CookieSameSite = "lax"
    COOKIE_DOMAIN: str | None = None
    #: Vida de la cookie de refresh. La cookie de acceso usa el ``expires_in``
    #: real que devuelve Supabase.
    REFRESH_COOKIE_MAX_AGE_SECONDS: int = 60 * 60 * 24 * 30

    # ---- CSRF -----------------------------------------------------------
    CSRF_SECRET: SecretStr = SecretStr("")
    CSRF_TOKEN_TTL_SECONDS: int = 60 * 60 * 8

    #: True cuando el secreto CSRF se genero al vuelo por no estar provisto.
    _csrf_secret_autogenerated: bool = PrivateAttr(default=False)

    # ------------------------------------------------------------------
    # Normalizacion
    # ------------------------------------------------------------------
    @field_validator("SUPABASE_URL")
    @classmethod
    def _strip_trailing_slash(cls, value: str) -> str:
        return value.rstrip("/")

    @field_validator("COOKIE_SAMESITE", mode="before")
    @classmethod
    def _lower_samesite(cls, value: object) -> object:
        return value.lower() if isinstance(value, str) else value

    @field_validator("COOKIE_DOMAIN", mode="before")
    @classmethod
    def _empty_domain_is_none(cls, value: object) -> object:
        if isinstance(value, str) and not value.strip():
            return None
        return value

    # ------------------------------------------------------------------
    # Reglas transversales
    # ------------------------------------------------------------------
    @model_validator(mode="after")
    def _validate_cookie_policy(self) -> Settings:
        # Requisito de los navegadores: SameSite=None solo se acepta junto con
        # Secure. Se falla de forma explicita en vez de degradar en silencio.
        if self.COOKIE_SAMESITE == "none" and not self.COOKIE_SECURE:
            raise ValueError(
                "COOKIE_SAMESITE=none exige COOKIE_SECURE=true; "
                "los navegadores descartan la cookie en caso contrario."
            )
        return self

    @model_validator(mode="after")
    def _ensure_csrf_secret(self) -> Settings:
        """Evita firmar con clave vacia fuera de produccion.

        Si no se provee ``CSRF_SECRET`` en un entorno no productivo se genera
        uno efimero: la proteccion CSRF sigue activa durante la sesion del
        proceso y los tokens dejan de ser validos al reiniciar. En produccion
        no se genera nada: la validacion de abajo exige un secreto explicito.
        """
        if not self.CSRF_SECRET.get_secret_value() and self.APP_ENV is not AppEnv.PRODUCTION:
            self.CSRF_SECRET = SecretStr(secrets.token_urlsafe(48))
            self._csrf_secret_autogenerated = True
        return self

    @model_validator(mode="after")
    def _validate_production_hardening(self) -> Settings:
        if self.APP_ENV is not AppEnv.PRODUCTION:
            return self

        problems: list[str] = []
        if not self.COOKIE_SECURE:
            problems.append("COOKIE_SECURE debe ser true en produccion")
        if len(self.CSRF_SECRET.get_secret_value()) < MIN_CSRF_SECRET_LENGTH:
            problems.append(f"CSRF_SECRET debe tener al menos {MIN_CSRF_SECRET_LENGTH} caracteres")
        if not self.SUPABASE_URL:
            problems.append("SUPABASE_URL es obligatorio")
        if not self.SUPABASE_PUBLISHABLE_KEY.get_secret_value():
            problems.append("SUPABASE_PUBLISHABLE_KEY es obligatorio")
        if problems:
            raise ValueError("; ".join(problems))
        return self

    # ------------------------------------------------------------------
    # Derivados
    # ------------------------------------------------------------------
    @property
    def is_production(self) -> bool:
        return self.APP_ENV is AppEnv.PRODUCTION

    @property
    def frontend_origins(self) -> list[str]:
        """Origenes CORS permitidos. El comodin se rechaza explicitamente."""
        origins = [item.strip() for item in self.FRONTEND_ORIGINS.split(",") if item.strip()]
        if "*" in origins:
            raise ConfigurationError(
                "FRONTEND_ORIGINS no admite el comodin porque CORS se sirve con "
                "allow_credentials=true. Declare los origenes exactos."
            )
        return origins

    @property
    def supabase_configured(self) -> bool:
        return bool(self.SUPABASE_URL and self.SUPABASE_PUBLISHABLE_KEY.get_secret_value())

    @property
    def database_configured(self) -> bool:
        return bool(self.DATABASE_URL.get_secret_value())

    @property
    def storage_configured(self) -> bool:
        """True cuando se puede escribir en Supabase Storage."""
        return bool(
            self.SUPABASE_URL
            and self.SUPABASE_SECRET_KEY.get_secret_value()
            and self.SUPABASE_STORAGE_BUCKET
        )

    @property
    def csrf_configured(self) -> bool:
        return bool(self.CSRF_SECRET.get_secret_value())

    @property
    def csrf_secret_autogenerated(self) -> bool:
        return self._csrf_secret_autogenerated


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Devuelve la configuracion resuelta (memoizada por proceso)."""
    return Settings()
